"""CLI tool to generate LAMMPS input files and setup scripts."""

import argparse
import os
import sys


def generate_lammps_input(checkpoint_path: str, output_dir: str = '.',
                          max_radius: float = 5.0,
                          atomic_energy_file: str = None,
                          atomic_energy_keys: list = None,
                          atomic_energy_values: list = None,
                          device: str = 'cuda',
                          embed_size: list = None,
                          output_size: int = 8,
                          type_to_Z: dict = None):
    """
    Generate LAMMPS input script and Python interface file.

    Args:
        checkpoint_path: Path to model checkpoint
        output_dir: Output directory for generated files
        max_radius: Maximum radius for neighbor search
        atomic_energy_file: Path to atomic energy CSV file
        atomic_energy_keys: List of atomic numbers for custom E0 (e.g. [1, 8])
        atomic_energy_values: List of atomic energies in eV (e.g. [-13.6, -75.0])
        device: Device to use (cuda/cpu)
        embed_size: Hidden layer sizes for readout MLP
        output_size: Output size for atom readout MLP
        type_to_Z: Optional dict LAMMPS type id -> atomic number Z (e.g. {1: 1, 2: 8})
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Get absolute paths
    checkpoint_path = os.path.abspath(checkpoint_path)
    if atomic_energy_file:
        atomic_energy_file = os.path.abspath(atomic_energy_file)
    
    # Path to the lammps_potential.py module
    script_dir = os.path.dirname(os.path.abspath(__file__))
    potential_module = os.path.join(
        os.path.dirname(os.path.dirname(script_dir)),
        'interfaces',
        'lammps_potential.py'
    )

    # Output file paths (define early so they can be referenced below)
    input_file = os.path.join(output_dir, 'lammps_input.in')
    init_file = os.path.join(output_dir, 'lammps_potential.py')
    init_basename = os.path.basename(init_file)
    
    # Generate LAMMPS input script
    lammps_input = f"""# LAMMPS input script for FusedEquiTensorPot
# Generated automatically

# Initialize Python interface (source = execute the file)
python source {init_basename}

# Set up Python potential
# Note: Adjust the path to lammps_potential.py if needed
fix 1 all python/invoke 1 1 1 {init_basename} lammps_potential_init lammps_potential

# Set pair style
pair_style python 1
pair_coeff * *

# Note: Make sure to set up your system (atoms, box, etc.) before running
# Example:
# read_data your_data_file.data
# or
# create_atoms 1 random 100 12345 NULL

# Run simulation
# run 1000
"""
    
    # Generate Python initialization script
    # Get the package root directory
    package_root = os.path.dirname(os.path.dirname(os.path.dirname(potential_module)))
    
    embed_size_arg = f"{embed_size}" if embed_size is not None else "None"
    aek_arg = f"{atomic_energy_keys}" if atomic_energy_keys is not None else "None"
    aev_arg = f"{atomic_energy_values}" if atomic_energy_values is not None else "None"
    type_to_z_arg = f"{type_to_Z}" if type_to_Z is not None else "None"
    python_init = f"""# Python initialization script for LAMMPS
# This file is automatically generated
# DO NOT EDIT MANUALLY - Regenerate using: mff-lammps

import sys
import os

# Add the mace_ictc package to path
package_dir = r"{package_root}"
if package_dir not in sys.path:
    sys.path.insert(0, package_dir)

# Import functions that LAMMPS will call by name from THIS file's namespace.
from mace_ictc.interfaces.lammps_potential import lammps_potential_init, lammps_potential

# Initialize potential
lammps_potential_init(
    r"{checkpoint_path}",
    device="{device}",
    max_radius={max_radius},
    atomic_energy_file={f'r"{atomic_energy_file}"' if atomic_energy_file else 'None'},
    atomic_energy_keys={aek_arg},
    atomic_energy_values={aev_arg},
    embed_size={embed_size_arg},
    output_size={output_size},
    type_to_Z={type_to_z_arg}
)
"""
    
    # Write files
    with open(input_file, 'w') as f:
        f.write(lammps_input)
    
    with open(init_file, 'w') as f:
        f.write(python_init)
    
    print(f"Generated LAMMPS files:")
    print(f"  Input script: {input_file}")
    print(f"  Python init: {init_file}")
    print(f"\nUsage:")
    print(f"  1. Copy {init_file} to your LAMMPS working directory")
    print(f"  2. In your LAMMPS input script, add:")
    print(f"     python {os.path.basename(init_file)} input")
    print(f"     fix 1 all python/invoke 1 1 1 {os.path.basename(init_file)} lammps_potential_init lammps_potential")
    print(f"     pair_style python 1")
    print(f"     pair_coeff * *")


def main():
    """Main CLI function."""
    parser = argparse.ArgumentParser(
        description='Generate LAMMPS interface files for FusedEquiTensorPot'
    )
    parser.add_argument('checkpoint', type=str,
                       help='Path to model checkpoint (.pth file)')
    parser.add_argument('--output-dir', type=str, default='.',
                       help='Output directory for generated files (default: current directory)')
    parser.add_argument('--max-radius', type=float, default=5.0,
                       help='Maximum radius for neighbor search in Angstrom (default: 5.0)')
    parser.add_argument('--atomic-energy-file', type=str, default=None,
                       help='Path to atomic energy CSV file (fitted_E0.csv)')
    parser.add_argument('--device', type=str, default='cuda',
                       choices=['cuda', 'cpu'],
                       help='Device to use (default: cuda)')
    parser.add_argument('--embed-size', type=int, nargs='+', default=None,
                       help='Hidden layer sizes for readout MLP (default: 128 128 128)')
    parser.add_argument('--output-size', type=int, default=8,
                       help='Output size for atom readout MLP (default: 8)')
    parser.add_argument('--atomic-energy-keys', type=int, nargs='+', default=None,
                       help='Atomic numbers for custom E0 (e.g. 1 8)')
    parser.add_argument('--atomic-energy-values', type=float, nargs='+', default=None,
                       help='Atomic energies in eV for custom E0')
    parser.add_argument('--type-to-Z', type=str, default=None,
                       help='LAMMPS type id -> Z mapping as comma-sep pairs, e.g. "1:1,2:8"')
    
    args = parser.parse_args()
    
    if not os.path.exists(args.checkpoint):
        print(f"Error: Checkpoint file not found: {args.checkpoint}")
        sys.exit(1)
    
    type_to_z = None
    if args.type_to_Z:
        type_to_z = {}
        for part in args.type_to_Z.split(","):
            k, v = part.strip().split(":")
            type_to_z[int(k)] = int(v)
    
    generate_lammps_input(
        args.checkpoint,
        args.output_dir,
        args.max_radius,
        args.atomic_energy_file,
        args.device,
        args.embed_size,
        args.output_size,
        atomic_energy_keys=args.atomic_energy_keys,
        atomic_energy_values=args.atomic_energy_values,
        type_to_Z=type_to_z,
    )


if __name__ == '__main__':
    main()
